# Generated by Django 3.0.8 on 2020-07-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
